# Generated by Django 5.0.3 on 2024-05-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='age_limit',
            field=models.CharField(choices=[('2-4', '2-4'), ('6-8', '6-8'), ('10-12', '10-12')], max_length=255),
        ),
    ]
