# Generated by Django 5.0.4 on 2024-05-13 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_story_age_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], default='English', max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='rate',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_who_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='age_limit',
            field=models.CharField(choices=[('2-5', '2-5'), ('6-9', '6-9'), ('10-12', '10-12')], max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(null=True, upload_to='PDFs/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Animals', 'Animals'), ('Fantasy', 'Fantasy'), ('Science', 'Science')], default='Adventure', max_length=255),
        ),
    ]
