# Generated by Django 5.0.3 on 2024-05-16 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_comment_updated_at_comment_story_story_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='story_which_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='myapp.story'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user_who_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL),
        ),
    ]
