# Generated by Django 5.0.3 on 2024-05-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_rate_story_which_rate_alter_rate_user_who_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='amount',
            field=models.FloatField(),
        ),
    ]
